# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"

    #config.vm.provision :shell, path: "vagrant/bootstrap.sh", run: 'once'
    config.vm.provision "shell",
        inline: "curl https://raw.githubusercontent.com/dhsathiya/dotfiles/master/Vagrant/bootstrap.sh | bash",
        privileged: true


    config.vm.network "private_network", ip: "192.168.11.10"
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 443, host: 443
    #config.vm.network "forwarded_port", guest: 9100, host: 9100 # Node Exporter
    #config.vm.network "forwarded_port", guest: 9090, host: 9090 # Prometheus
    #config.vm.network "forwarded_port", guest: 3000, host: 3000 # Grafana

    #config.ssh.username = 'root'
    #config.ssh.password = 'vagrant'
    #config.ssh.insert_key = 'true'

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

end
